#!/bin/bash

# the first argument should be the tex file, either with or without extension
pdffile="$1"

# run pdflatex and bibtex, and open or reload the pdf  in Skim
/usr/bin/osascript << EOF
  set theFile to POSIX file "${pdffile}" as alias
  set thePath to POSIX path of theFile
  tell application "Skim"
    activate
    set theDocs to get documents whose path is thePath
    try
      if (count of theDocs) > 0 then revert theDocs
    end try
  end tell
EOF